[ssh]
enabled = true
port = 22
# The maximum number of seconds a connection can take.
# A value of 0 means no timeout.
max_timeout = 0
# The number of seconds a connection can be idle before it is closed.
idle_timeout = 120

[api]
port = 3000
enabled = true
